version: "3"

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SQL_SA_PASS}"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
